clear
    echo "脚本更新日志"
    echo  "------------------------"
    echo "2024-03-14   v1.0.0"
    echo "1.延续花娘子一键。"
    echo "2.这里增加授权站的搭建."
    echo "3.LDNMP项目新增Miaooo朋友圈授权搭建"
    echo  "------------------------"
    echo "2024-03-15   v1.0.1"
    echo "1.LDNMP项目新增至尊码支付授权搭建"
    echo "2.LDNMP项目新增个人导航搭建"
    echo "3.LDNMP项目新增个人主页搭建"
    echo "4.LDNMP项目新增Files Photo Gallery搭建"
    echo  "------------------------"
